### ISSUE TITLE
Error on a few commands in cli.js

### ISSUE THREAD

**Issue by sjaakbanaan** [jangxx/node-magichome#13]
I get the following error when I run commands like `list_patterns`, `discover` and `help`:

PS C:\Users\bleep> magic-home list_patterns
C:\Users\bleep\AppData\Roaming\npm\node_modules\magic-home\cli.js:84
if (args.length > command.args.length) {                               ^

TypeError: Cannot read property 'length' of undefined
    at Object.<anonymous> (C:\Users\bleep\AppData\Roaming\npm\node_modules\magic-home\cli.js:84:32)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

I'm on Win 10, PowerShell with a fresh node.js/npm install.

**Comment by jangxx** [comment]
Fixed in version 2.0.3
