### ISSUE TITLE
Edited ack mask still getting time out error

### ISSUE THREAD

**Issue by Jpinales97** [jangxx/node-magichome#42]
I have a model AK001-ZJ2101 Bulb, using the python library I was able to change color, but whenever I try to change the color I end up with the same error. I have changed the ack mask according to what did and didn't get a response, but I still got the same errors

Code that I used
const { Control } = require('magic-home');

let light = new Control("192.168.1.177")
// light.turnOff()
light.turnOn()
light.setColor(255,0,0)
light.setColorAndWarmWhite(255,0,0,13)
light.setColorAndWhites(255,0,0,13,13)`
const { Control } = require('magic-home');

at Control._handleCommandTimeout (C:\Users\XXX\Documents\Code\JavaScript\HAL\Trial Folder\node_modules\magic-home\lib\Control.js:217:12)
    at Timeout._onTimeout (C:\Users\XXX\Documents\Code\JavaScript\HAL\Trial Folder\node_modules\magic-home\lib\Control.js:244:12)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:15640) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:15640) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:15640) UnhandledPromiseRejectionWarning: Error: Command timed out
    at Control._handleCommandTimeout (C:\Users\Helquin\Documents\Code\JavaScript\HAL\Trial Folder\node_modules\magic-home\lib\Control.js:217:12)
    at Timeout._onTimeout (C:\Users\Helquin\Documents\Code\JavaScript\HAL\Trial Folder\node_modules\magic-home\lib\Control.js:244:12)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
(node:15640) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:15640) UnhandledPromiseRejectionWarning: Error: Command timed out
    at Control._handleCommandTimeout (C:\Users\XXX\Documents\Code\JavaScript\HAL\Trial Folder\node_modules\magic-home\lib\Control.js:217:12)
    at Timeout._onTimeout (C:\Users\XXX\Documents\Code\JavaScript\HAL\Trial Folder\node_modules\magic-home\lib\Control.js:244:12)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
(node:15640) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)

**Comment by jangxx** [comment]
This device is unsupported right now, see https://github.com/jangxx/node-magichome/issues/39

**Comment by jangxx** [comment]
Version 2.8.0 adds support for these new devices with the `ControlAddressable` class, so this can be closed.
